apiVersion: v2
name: Traefik Server
description: Traefik server with overrides
type: application
version: 0.0.1
appVersion: 1.16.0

dependencies:
  - name: traefik
    version: 10.1.1
    repository: https://helm.traefik.io/traefik

